import Head from 'next/head';
import styles from './../styles/cart.module.css';
import Layout from '../components/layout/layout.component';
import { useSelector } from 'react-redux';

import {
  selectCartItems,
  selectCartTotal,
} from './../store/cart/cart.selector';

import CartItem from '../components/cart-item/cart-item.component';

const Cart = () => {
  const cartItems = useSelector(selectCartItems);
  const cartTotal = useSelector(selectCartTotal);

  return (
    <>
      <Layout>
        <Head>
          <title>Jamrock Kitchen | Cart</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <section className='container'>
          <h1>Cart</h1>
          <p>Cart Total: ${cartTotal.toFixed(2)}</p>
          <section className={styles.cart}>
            {cartItems.map((cartItem: any, id: number) => {
              return <CartItem key={id} cartItem={cartItem} id={id} />;
            })}
          </section>
        </section>
      </Layout>
    </>
  );
};

export default Cart;
