import Head from 'next/head';
import styles from './../styles/cart.module.css';
import Layout from '../components/layout/layout.component';
import { useSelector } from 'react-redux';

import {
  selectCartItems,
  selectCartTotal,
} from './../store/cart/cart.selector';

import CartItem from '../components/cart-item/cart-item.component';

import { selectCurrentUser } from '../store/user/user.selector';
import { createOrder } from '../utils/firebase';

const Cart = () => {
  const cartItems = useSelector(selectCartItems);
  const cartTotal = useSelector(selectCartTotal);
  const currentUser = useSelector(selectCurrentUser);
  const handleCreateOrder = () =>
    createOrder(
      cartItems,
      currentUser.uid,
      Number((cartTotal * 0.05 + cartTotal).toFixed(2))
    );

  return (
    <>
      <Layout>
        <Head>
          <title>Jamrock Kitchen | Cart</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <section className={`container ${styles.cart}`}>
          {/* <h1>Cart</h1>
          <p>Cart Total: ${cartTotal.toFixed(2)}</p> */}
          <section>
            {cartItems.map((cartItem: any, id: number) => {
              return <CartItem key={id} cartItem={cartItem} id={id} />;
            })}
          </section>
          <section className={styles.cart_total}>
            <div>
              <h1>Cart</h1>
              <p>
                Cart Total:{' '}
                <span className={styles.cost}>${cartTotal.toFixed(2)}</span>
              </p>
              <p>
                Total GST:{' '}
                <span className={styles.cost}>
                  ${(cartTotal * 0.05).toFixed(2)}
                </span>
              </p>
              <p>
                Final Total:{' '}
                <span className={styles.cost}>
                  ${(cartTotal * 0.05 + cartTotal).toFixed(2)}
                </span>
              </p>
            </div>
            <div>
              <button onClick={handleCreateOrder}>Check Out</button>
            </div>
          </section>
        </section>
      </Layout>
    </>
  );
};

export default Cart;
