import Head from "next/head";

import Layout from "../components/layout/layout.component";
import LoginForm from "../components/login-form/login.component";

const Login = () => {
  return (
    <>
      <Head>
        <title>Jamrock Kitchen | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="container">
          <LoginForm />
        </section>
      </Layout>
    </>
  );
};

export default Login;
