import Head from 'next/head';
import { useState, ChangeEvent, FormEvent } from 'react';
import Layout from '../components/layout/layout.component';
import { signInAuthUserWithEmailAndPassword } from '../utils/firebase';
import styles from './../styles/login.module.css';
import { useRouter } from 'next/router';

type FormFields = {
  email: string;
  password: string;
};

const defaultFormFields: FormFields = {
  email: '',
  password: '',
};

const Login = () => {
  const router = useRouter();
  const [formFields, setFormFields] = useState<FormFields>(defaultFormFields);
  const { email, password } = formFields;

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target as HTMLInputElement;
    setFormFields({ ...formFields, [name]: value });
  };
  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    const user = await signInAuthUserWithEmailAndPassword(email, password);
    if (user) {
      router.push('orders');
    }
  };
  return (
    <>
      <Head>
        <title>Jamrock Kitchen | Login</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <section className='container'>
          <div className={styles.login}>
            <h1>Login</h1>
            <form onSubmit={handleSubmit}>
              <div>
                <label htmlFor=''>Email</label>
                <input
                  type='email'
                  name='email'
                  onChange={handleChange}
                  value={email}
                />
              </div>
              <div>
                <label htmlFor=''>Password</label>
                <input
                  type='password'
                  name='password'
                  onChange={handleChange}
                  value={password}
                />
              </div>
              <button>Login</button>
            </form>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default Login;
