import Head from "next/head";

import Layout from "../components/layout/layout.component";
import RegisterForm from "../components/register-form/register-form.component";
const Register = () => {
  return (
    <>
      <Head>
        <title>Jamrock Kitchen | Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="container">
          <RegisterForm />
        </section>
      </Layout>
    </>
  );
};

export default Register;
